[package]
authors = ['Mangata team']
name = "xyk-runtime-api"
version = "2.0.0"
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { version = '2.0.0', default-features = false, git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-runtime = { default-features = false, version = '2.0.0' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
frame-support = { default-features = false, version = '2.0.0' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
frame-system = { default-features = false, version = '2.0.0' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-core = { default-features = false, version = '2.0.0' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std"]
std = [
    "serde",
    "sp-api/std",
    "codec/std",
    "sp-runtime/std",
    "frame-support/std",
    'frame-system/std',
]
