[package]
name = "substrate-frame-rpc-system"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME's system exposed over Substrate RPC"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-client-api = "2.0.0"
codec = { package = "parity-scale-codec", version = "1.3.1" }
futures = { version = "0.3.4", features = ["compat"] }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
log = "0.4.8"
serde = { version = "1.0.101", features = ["derive"] }
sp-runtime = "2.0.0"
sp-api = "2.0.0"
frame-system-rpc-runtime-api = "2.0.0"
sp-core = "2.0.0"
sp-blockchain = "2.0.0"
sp-transaction-pool = "2.0.0"
sp-block-builder = "2.0.0"
sc-rpc-api = "0.8.0"

[dev-dependencies]
#substrate-test-runtime-client = "2.0.0"
sp-tracing = "2.0.0"
sc-transaction-pool = "2.0.0"
