version: "3.7"
networks:
    test_net:
      ipam:
        driver: default
        config:
          - subnet: 10.0.0.0/24

services:
  relay_alice:
    environment:
      - RUST_LOG=debug,sync=info,afg=info,libp2p_swarm=info,multistream_select=info,libp2p_core=info,sub-libp2p=info,libp2p_tcp=info,wasm_overrides=info,wasm-heap=info,libp2p_ping=info,runtime=trace
    build:
      context: ../../
      dockerfile: ./devops/dockerfiles/node-and-runtime/relay.dockerfile
    entrypoint: ""
    command: polkadot --alice --validator --tmp --chain /config/spec.json --port 30333  --unsafe-ws-external --rpc-port=40333 --unsafe-rpc-external --rpc-cors=all --ws-port 9944
    volumes:
      - ./config:/config
    ports:
      - 9944:9944
    networks:
        test_net:
          ipv4_address: 10.0.0.2

  relay_bob:
    build:
      context: ../../
      dockerfile: ./devops/dockerfiles/node-and-runtime/relay.dockerfile
        #environment:
        #- RUST_LOG=debug,sync=info,afg=info,libp2p_swarm=info,multistream_select=info,libp2p_core=info,sub-libp2p=info,libp2p_tcp=info,wasm_overrides=info,wasm-heap=info,libp2p_ping=info,runtime=debug
    entrypoint: ""
    tty: true
    command: > 
      bash -c "
      HEADER='Content-Type:application/json';
      PAYLOAD='{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"system_localPeerId\"}';
      while ! curl --silent --connect-timeout 0.3 -H \"$$HEADER\" -d \"$$PAYLOAD\" http://relay_alice:40333 > /dev/null ; do
        echo waiting for Alice relay node;
        sleep 0.3;
      done;
      NODE_ID=$$(curl --connect-timeout 0.3 -H \"$$HEADER\" -d \"$$PAYLOAD\" http://relay_alice:40333 | jq -r '.result');
      echo NODE ID: $$NODE_ID;
      polkadot --bob --validator --tmp --chain /config/spec.json --port 30333  --ws-port 9944 --bootnodes /ip4/10.0.0.2/tcp/30333/p2p/$$NODE_ID --unsafe-ws-external --unsafe-rpc-external --rpc-cors=all;
      "
    volumes:
      - ./config:/config
    networks:
        test_net:
          ipv4_address: 10.0.0.3


  register:
    environment:
      - STATE_FILE=/config/genesis-state
      - WASM_FILE=/config/genesis-wasm
    build:
      context: ../../
      dockerfile: devops/dockerfiles/node-and-runtime/para.dockerfile
    command: bash -c "sleep 5 && node index.js"
    volumes:
      - ./config:/config
    networks:
        test_net:
          ipv4_address: 10.0.0.4

  para_alice:
    environment:
      - RUST_LOG=debug,sync=info,afg=info,libp2p_swarm=info,multistream_select=info,libp2p_core=info,sub-libp2p=info,libp2p_tcp=info,wasm_overrides=info,wasm-heap=info,libp2p_ping=info,runtime=debug
    image: dev
    command: >
      bash -c "
      /code/target/release/mangata-node export-genesis-state > /config/genesis-state;
      /code/target/release/mangata-node export-genesis-wasm > /config/genesis-wasm;
      /code/target/release/mangata-node --alice --collator --force-authoring --tmp --port 30333
      --ws-port 9944 --unsafe-ws-external --unsafe-rpc-external
      --rpc-cors=all -- --execution wasm --chain /config/spec.json
      --port 30334 --ws-port 9945
      "
    volumes:
      - ./config:/config
      - ../../:/code
    ports:
      - 8844:9944
    networks:
        test_net:
          ipv4_address: 10.0.0.5

  para_bob:
    image: dev
    command: >
      /code/target/release/mangata-node --bob --rpc-cors=all 
      --collator --unsafe-ws-external --unsafe-rpc-external  
      --force-authoring --tmp --port 30333 --ws-port 9944 -- 
      --execution wasm --chain /config/spec.json
      --port 30334
    volumes:
      - ./config:/config
      - ../../:/code
    networks:
        test_net:
          ipv4_address: 10.0.0.6


  ui:
    build:
      context: ../../
      dockerfile: devops/dockerfiles/node-and-runtime/ui.dockerfile
    ports:
      - 3000:3000
    networks:
        test_net:
          ipv4_address: 10.0.0.10


