version: "3.7"
networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

services:
  relay_alice:
    environment:
      - ${RUST_LOG:-info}
    image: parity/polkadot:v0.9.19
    command:
      - "--alice"
      - "--validator"
      - "--base-path=/tmp/relay_alice"
      - "--port=30333"
      - "--ws-port=9944"
      - "--chain=/etc/mangata/spec.json"
      - "--unsafe-ws-external"
      - "--rpc-port=40333"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000001"
    volumes:
      - ./config:/etc/mangata
    ports:
      - 9944:9944
      - 9933:9933

    networks:
      test_net:
        ipv4_address: 10.0.0.2

  relay_bob:
    image: parity/polkadot:v0.9.19
    environment:
      - ${RUST_LOG:-info}
    command:
      - "--bob"
      - "--validator"
      - "--base-path=/tmp/relay_bob"
      - "--port=30333"
      - "--ws-port=9944"
      - "--chain=/etc/mangata/spec.json"
      - "--bootnodes=/dns/relay_alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000002"
    volumes:
      - ./config:/etc/mangata
    networks:
      test_net:
        ipv4_address: 10.0.0.3

  register:
    image: mangatasolutions/parachain-register:0.1
    command: bash -c "sleep 10s && node index.js"
    environment:
      - STATE_FILE=/config/genesis-state
      - WASM_FILE=/config/genesis-wasm
      - COLLATOR_ADDR=ws://relay_alice:9944
    volumes:
      - ./config:/config
    networks:
      test_net:
        ipv4_address: 10.0.0.4

  para_alice:
    image: ${PARACHAIN_DOCKER_IMAGE:-mangatasolutions/mangata-node:latest}
    environment:
      - ${RUST_LOG:-info}
      - RUST_BACKTRACE=1
      - LD_PRELOAD=${LD_PRELOAD}
    entrypoint: ""
    command: >
      bash -xc "
      /mangata/node export-genesis-state > /etc/mangata/genesis-state;
      /mangata/node export-genesis-wasm > /etc/mangata/genesis-wasm;
      /mangata/node
      --alice
      --collator
      --force-authoring
      --base-path=/tmp/para_alice
      --port=30333
      --ws-port=9944
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors=all
      --node-key=0000000000000000000000000000000000000000000000000000000000000003
      --
      --execution=wasm
      --chain=/etc/mangata/spec.json
      --bootnodes=/dns/relay_alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      "
    volumes:
      - ./config:/etc/mangata
    ports:
      - 9955:9944
      - 9966:9933
    networks:
      test_net:
        ipv4_address: 10.0.0.5

  para_bob:
    image: ${PARACHAIN_DOCKER_IMAGE:-mangatasolutions/mangata-node:latest}
    environment:
      - ${RUST_LOG:-info}
      - LD_PRELOAD=${LD_PRELOAD}
    entrypoint: ""
    command:
      - "/mangata/node"
      - "--bob"
      - "--collator"
      - "--force-authoring"
      - "--base-path=/tmp/para_bob"
      - "--port=30333"
      - "--ws-port=9944"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000004"
      - "--bootnodes=/dns/para_alice/tcp/30333/p2p/12D3KooWKpDhPnax8CyJvVh77Z5T84a8EWZvY7c9Z7pZ1tk6sLBD"
      - "--"
      # relay
      - "--execution=wasm"
      - "--chain=/etc/mangata/spec.json"
      - "--bootnodes=/dns/relay_alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
    volumes:
      - ./config:/etc/mangata
    networks:
      test_net:
        ipv4_address: 10.0.0.6
    cap_add:
      - SYS_ADMIN

  ui:
    build:
      context: ../../
      dockerfile: devops/dockerfiles/polkadot-ui/Dockerfile
    ports:
      - 3000:3000
    networks:
      test_net:
        ipv4_address: 10.0.0.10

  sidecar:
    image: parity/substrate-api-sidecar:latest
    container_name: para_alice_sidecar
    depends_on:
      - para_alice
    ports:
      - "8080:8080"
    networks:
      test_net:
        ipv4_address: 10.0.0.11
    environment:
      SAS_SUBSTRATE_WS_URL: ws://para_alice:9944
      SAS_EXPRESS_LOG_MODE: all
