services:
  para_alice:
    image: ${PARACHAIN_DOCKER_IMAGE:-mangatasolutions/mangata-node:rococo-latest}
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=1
      - LD_PRELOAD=${LD_PRELOAD}
    entrypoint: ""
    command: >
      /mangata/node
      --alice 
      --collator 
      --force-authoring 
      --chain ${PARA_CHAIN:-mangata-rococo-local-testnet}
      --bootnodes=/dns/para_bob/tcp/30333/p2p/12D3KooWSsChzF81YDUKpe9Uk5AHV5oqAaXAcWNSPYgoLauUk4st
      --base-path /tmp/para_alice
      --port 30333 
      --ws-port 9944 
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors=all
      --node-key=0000000000000000000000000000000000000000000000000000000000000003
      -- 
      --execution wasm 
      --chain ${RELAY_CHAIN:-rococo-local}
      --bootnodes=/dns/relay_alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      --port 30334
      --ws-port 8844
    volumes:
      - ./config:/etc/mangata
    ports:
      - 8844:9944
      - 40444:30333

  para_bob:
    image: ${PARACHAIN_DOCKER_IMAGE:-mangatasolutions/mangata-node:rococo-latest}
    environment:
      - ${RUST_LOG:-info}
      - LD_PRELOAD=${LD_PRELOAD}
    entrypoint: ""
    command: >
      /mangata/node
      --bob 
      --collator 
      --force-authoring 
      --chain ${PARA_CHAIN:-mangata-rococo-local-testnet}
      --bootnodes=/dns/para_alice/tcp/30333/p2p/12D3KooWKpDhPnax8CyJvVh77Z5T84a8EWZvY7c9Z7pZ1tk6sLBD
      --base-path /tmp/para_bob
      --port=30333 
      --ws-port=9944 
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors=all
      --node-key=0000000000000000000000000000000000000000000000000000000000000004
      -- 
      --execution wasm 
      --chain ${RELAY_CHAIN:-rococo-local}
      --bootnodes=/dns/relay_alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      --port 30334
      --ws-port 8844
    volumes:
      - ./config:/etc/mangata
