services:
  relay_alice:
    image: ${RELAYCHAIN_DOCKER_IMAGE:-parity/polkadot:v0.9.19}
    user: root
    command: >
      --alice
      --validator
      --base-path /tmp/relay_alice
      --chain ${RELAY_CHAIN:-rococo-local}
      --public-addr=/ip4/127.0.0.1/tcp/30333
      --port 30333
      --ws-port 9944
      --unsafe-ws-external
      --rpc-port=40333
      --unsafe-rpc-external
      --rpc-cors=all
      --node-key=0000000000000000000000000000000000000000000000000000000000000001
    volumes:
      - ./config:/etc/mangata
    ports:
      - 9944:9944
      - 30333:30333

  relay_bob:
    image: ${RELAYCHAIN_DOCKER_IMAGE:-parity/polkadot:v0.9.19}
    user: root
    command: >
      --bob
      --validator
      --base-path /tmp/relay_bob
      --chain ${RELAY_CHAIN:-rococo-local}
      --public-addr=/ip4/127.0.0.1/tcp/30334
      --bootnodes=/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      --port 30333
      --ws-port 9944
      --node-key=0000000000000000000000000000000000000000000000000000000000000002
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors=all
    volumes:
      - ./config:/etc/mangata
    ports:
      - 9945:9944
      - 30334:30333

  gen-wasm-and-state:
    image: ${PARACHAIN_DOCKER_IMAGE:-mangatasolutions/mangata-node:latest}
    environment:
      - ${RUST_LOG:-info}
    entrypoint: ""
    command: >
      bash -xec "
      /mangata/node export-genesis-state --chain=${PARA_CHAIN:-mangata-rococo-local-testnet} 2>/dev/null > /etc/mangata/state &&
      /mangata/node export-genesis-wasm --chain=${PARA_CHAIN:-mangata-rococo-local-testnet} 2>/dev/null > /etc/mangata/wasm
      "
    volumes:
      - ./config:/etc/mangata

  register:
    image: mangatasolutions/parachain-register:0.1
    depends_on:
      - gen-wasm-and-state
    command: bash -c "sleep 3s && node index.js"
    environment:
      - STATE_FILE=/config/state
      - WASM_FILE=/config/wasm
      - COLLATOR_ADDR=ws://relay_alice:9944
    volumes:
      - ./config:/config

