[package]
name = "common-runtime"
version = "4.0.0"
authors = ["Mangata Team"]
edition = "2018"
license = "Unlicense"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }

[dependencies]
hex-literal = { version = '0.3.1' }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4.20", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.137", optional = true, features = ["derive"] }
smallvec = "1.6.1"
static_assertions = "1.1.0"

# Local Dependencies
pallet-xyk = { path = '../../pallets/xyk', default-features = false, version = '0.1.0' }
pallet-proof-of-stake = { path = '../../pallets/proof-of-stake', default-features = false, version = '0.1.0' }
pallet-bootstrap = { path = '../../pallets/bootstrap', default-features = false, version = '0.1.0' }
xyk-runtime-api = { path = '../../pallets/xyk/runtime-api', default-features = false, version = '2.0.0' }
pallet-sudo-origin = { path = '../../pallets/sudo-origin', default-features = false }
pallet-issuance = { path = '../../pallets/issuance', default-features = false }
pallet-multipurpose-liquidity = { path = '../../pallets/multipurpose-liquidity', default-features = false }
pallet-maintenance = { path = '../../pallets/maintenance', default-features = false }
pallet-fee-lock = { path = '../../pallets/fee-lock', default-features = false}
mangata-support = { default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }

# Substrate Dependencies
## Substrate Primitive Dependencies
mangata-types = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-api = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-block-builder = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-consensus-aura = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-core = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-inherents = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-io = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-offchain = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-runtime = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-session = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-std = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-transaction-pool = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-utility-mangata = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-ver = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-version = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-weights = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }

## Substrate FRAME Dependencies
frame-benchmarking = { git = "https://github.com/mangata-finance/substrate", default-features = false, optional = true, branch = "mangata-dev" }
frame-executive = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
frame-try-runtime = { git = "https://github.com/mangata-finance/substrate", default-features = false, optional = true, branch = "mangata-dev" }
frame-support = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
frame-system = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
frame-system-benchmarking = { git = "https://github.com/mangata-finance/substrate", default-features = false, optional = true, branch = "mangata-dev" }
frame-system-rpc-runtime-api = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
ver-api = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }

## Substrate Pallet Dependencies
pallet-aura = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-authorship = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-session = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-sudo-mangata = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-timestamp = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-transaction-payment-mangata = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-transaction-payment-mangata-rpc-runtime-api = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-treasury = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-collective-mangata = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-vesting-mangata = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-proxy = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-identity = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
pallet-root-testing = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }

# Open-Runtime-Module-Library Dependencies
orml-tokens = { default-features = false, version = "0.4.1-dev", git = "https://github.com/mangata-finance/open-runtime-module-library", branch = "mangata-dev" }
orml-traits = { default-features = false, version = "0.4.1-dev", git = "https://github.com/mangata-finance/open-runtime-module-library", branch = "mangata-dev" }
orml-xtokens = { default-features = false, version = "0.4.1-dev", git = "https://github.com/mangata-finance/open-runtime-module-library", branch = "mangata-dev" }
orml-xcm-support = { default-features = false, version = "0.4.1-dev", git = "https://github.com/mangata-finance/open-runtime-module-library", branch = "mangata-dev" }
orml-unknown-tokens = { default-features = false, version = "0.4.1-dev", git = "https://github.com/mangata-finance/open-runtime-module-library", branch = "mangata-dev" }
orml-xcm = { default-features = false, version = "0.4.1-dev", git = "https://github.com/mangata-finance/open-runtime-module-library", branch = "mangata-dev" }
orml-asset-registry = { default-features = false, version = "0.4.1-dev", git = "https://github.com/mangata-finance/open-runtime-module-library", branch = "mangata-dev" }

# Cumulus dependencies
cumulus-pallet-aura-ext = { git = 'https://github.com/mangata-finance/cumulus', branch = "mangata-dev", default-features = false }
cumulus-pallet-dmp-queue = { git = 'https://github.com/mangata-finance/cumulus', branch = "mangata-dev", default-features = false }
cumulus-pallet-parachain-system = { git = 'https://github.com/mangata-finance/cumulus', branch = "mangata-dev", default-features = false }
cumulus-pallet-xcm = { git = 'https://github.com/mangata-finance/cumulus', branch = "mangata-dev", default-features = false }
cumulus-pallet-xcmp-queue = { git = 'https://github.com/mangata-finance/cumulus', branch = "mangata-dev", default-features = false }
cumulus-primitives-core = { git = 'https://github.com/mangata-finance/cumulus', branch = "mangata-dev", default-features = false }
cumulus-primitives-timestamp = { git = 'https://github.com/mangata-finance/cumulus', branch = "mangata-dev", default-features = false }
cumulus-primitives-utility = { git = 'https://github.com/mangata-finance/cumulus', branch = "mangata-dev", default-features = false }
parachain-info = { git = 'https://github.com/mangata-finance/cumulus', branch = "mangata-dev", default-features = false }
cumulus-pallet-session-benchmarking = { git = 'https://github.com/mangata-finance/cumulus', branch = "mangata-dev", default-features = false, optional = true }

# Polkadot Dependencies
polkadot-primitives = { git = "https://github.com/mangata-finance/polkadot", branch = "mangata-dev", default-features = false }
pallet-xcm = { git = "https://github.com/mangata-finance/polkadot", default-features = false, branch = "mangata-dev" }
polkadot-parachain = { git = "https://github.com/mangata-finance/polkadot", default-features = false, branch = "mangata-dev" }
polkadot-runtime-common = { git = "https://github.com/mangata-finance/polkadot", default-features = false, branch = "mangata-dev" }
xcm = { git = "https://github.com/mangata-finance/polkadot", default-features = false, branch = "mangata-dev" }
xcm-builder = { git = "https://github.com/mangata-finance/polkadot", default-features = false, branch = "mangata-dev" }
xcm-executor = { git = "https://github.com/mangata-finance/polkadot", default-features = false, branch = "mangata-dev" }

# Staking dependencies
parachain-staking = { default-features = false, git = "https://github.com/mangata-finance/moonbeam", branch = "mangata-dev" }

# Crowdloan dependencies
pallet-crowdloan-rewards = { default-features = false, git = "https://github.com/mangata-finance/crowdloan-rewards", branch = "mangata-dev" }

[features]
default = [
	"std",
]
std = [
	"codec/std",
	"serde",
	"scale-info/std",
	"log/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-ver/std",
	"sp-version/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-aura/std",
	"pallet-authorship/std",
	"pallet-proxy/std",
	"pallet-session/std",
	"pallet-sudo-mangata/std",
	"pallet-sudo-origin/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-mangata-rpc-runtime-api/std",
	"pallet-transaction-payment-mangata/std",
	"pallet-utility-mangata/std",
	"cumulus-pallet-aura-ext/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcm/std",
	"cumulus-pallet-xcmp-queue/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-timestamp/std",
	"cumulus-primitives-utility/std",
	"cumulus-pallet-dmp-queue/std",
	"cumulus-pallet-session-benchmarking/std",
	"frame-benchmarking/std",
	"frame-system-benchmarking/std",
	"frame-try-runtime/std",
	"polkadot-primitives/std",
	"sp-weights/std",
	"parachain-info/std",
	"polkadot-parachain/std",
	"polkadot-runtime-common/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
	"ver-api/std",
	"mangata-types/std",
	"orml-traits/std",
	"orml-tokens/std",
	"pallet-treasury/std",
	"pallet-xyk/std",
	"pallet-proof-of-stake/std",
	"pallet-bootstrap/std",
  	"xyk-runtime-api/std",
	"parachain-staking/std",
	"orml-xtokens/std",
	"orml-xcm-support/std",
	"orml-unknown-tokens/std",
	"orml-xcm/std",
	"orml-asset-registry/std",
	"pallet-issuance/std",
	"pallet-vesting-mangata/std",
	"pallet-crowdloan-rewards/std",
	"frame-system-rpc-runtime-api/std",
	"pallet-collective-mangata/std",
	"pallet-multipurpose-liquidity/std",
	"mangata-support/std",
	"pallet-fee-lock/std",
	"pallet-identity/std",
	"pallet-maintenance/std",
]


try-runtime = [
	"sp-runtime/try-runtime",
	"frame-support/try-runtime",
	"frame-try-runtime",
	"frame-executive/try-runtime",
	"frame-system/try-runtime",
	"polkadot-runtime-common/try-runtime",
	"pallet-multipurpose-liquidity/try-runtime",
	"cumulus-pallet-parachain-system/try-runtime",
	"pallet-timestamp/try-runtime",
	"parachain-info/try-runtime",
	"orml-tokens/try-runtime",
	"pallet-transaction-payment-mangata/try-runtime",
	"pallet-xyk/try-runtime",
	"pallet-proof-of-stake/try-runtime",
	"pallet-vesting-mangata/try-runtime",
	"pallet-crowdloan-rewards/try-runtime",
	"pallet-issuance/try-runtime",
	"pallet-authorship/try-runtime",
	"parachain-staking/try-runtime",
	"pallet-session/try-runtime",
	"pallet-aura/try-runtime",
	"cumulus-pallet-aura-ext/try-runtime",
	"cumulus-pallet-xcmp-queue/try-runtime",
	"pallet-xcm/try-runtime",
	"cumulus-pallet-xcm/try-runtime",
	"cumulus-pallet-dmp-queue/try-runtime",
	"orml-xtokens/try-runtime",
	"orml-unknown-tokens/try-runtime",
	"orml-xcm/try-runtime",
	"orml-asset-registry/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-sudo-mangata/try-runtime",
	"pallet-sudo-origin/try-runtime",
	"pallet-collective-mangata/try-runtime",
	"pallet-bootstrap/try-runtime",
	"pallet-utility-mangata/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-fee-lock/try-runtime",
	"pallet-identity/try-runtime",
	"pallet-maintenance/try-runtime",
	"pallet-root-testing/try-runtime"
]

fast-runtime = []

runtime-benchmarks = [
	"polkadot-primitives/runtime-benchmarks",
	"pallet-maintenance/runtime-benchmarks",
	"polkadot-parachain/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"orml-tokens/runtime-benchmarks",
	"orml-xtokens/runtime-benchmarks",
	"orml-asset-registry/runtime-benchmarks",
	"cumulus-pallet-session-benchmarking/runtime-benchmarks",
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"pallet-xyk/runtime-benchmarks",
	"pallet-proof-of-stake/runtime-benchmarks",
	"parachain-staking/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-collective-mangata/runtime-benchmarks",
	"pallet-crowdloan-rewards/runtime-benchmarks",
	"pallet-utility-mangata/runtime-benchmarks",
	"pallet-vesting-mangata/runtime-benchmarks",
	"pallet-issuance/runtime-benchmarks",
	"pallet-bootstrap/runtime-benchmarks",
	"pallet-multipurpose-liquidity/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-fee-lock/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
]
