[package]
name = "mangata-rpc-nonce"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME's system exposed over Substrate RPC"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
codec = { package = "parity-scale-codec", version = "3.0.0" }
futures = "0.3.21"
jsonrpsee = { version = "0.16.2", features = ["server"] }
log = "0.4.20"
sp-runtime = { version = "7.0.0", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
frame-system-rpc-runtime-api ={ version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-core ={ version = "7.0.0", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-blockchain ={ version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
ver-api ={ version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sc-transaction-pool-api ={ version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-block-builder ={ version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sc-rpc-api ={ version = "0.10.0-dev", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
