[package]
authors = ['Mangata team']
edition = '2018'
name = 'pallet-multipurpose-liquidity'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
log = { version = "0.4.14", default-features = false }
hex = { package = "rustc-hex", version = "2.1.0", default-features = false }
hex-literal = { version = "0.3.3", default-features = false }
serde = { version = "1.0.126", optional = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

frame-support = { default-features = false, version = '4.0.0-dev' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
frame-benchmarking = { default-features = false, version = '4.0.0-dev' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
frame-system = { default-features = false, version = '4.0.0-dev' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-runtime = { default-features = false, version = '6.0.0' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-core = { default-features = false, version = '6.0.0' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
sp-std = { version = "4.0.0-dev", default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
mangata-primitives = { default-features = false, version = '0.1.0' , path = '../../primitives/mangata'}
orml-tokens = {  default-features = false, version = '0.4.1-dev' , git = "https://github.com/mangata-finance/open-runtime-module-library", branch = "mangata-dev-v0.9.24" }

pallet-vesting-mangata = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev-v0.9.24" }
mp-multipurpose-liquidity = { path = '../../primitives/multipurpose-liquidity', default-features = false}
mp-traits = { path = '../../primitives/traits', default-features = false}
parachain-staking = { default-features = false, git = "https://github.com/mangata-finance/moonbeam.git", branch = "mangata-dev-v0.9.24" }

[dev-dependencies]
orml-traits = { default-features = false, version="0.4.1-dev" , git = "https://github.com/mangata-finance/open-runtime-module-library", branch = "mangata-dev-v0.9.24" }
sp-io = { default-features = false, version = '6.0.0' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.24" }
env_logger = "0.9.0"
serial_test = { version = "0.6.0", default-features = false }

[features]
default = ['std']
enable-trading = []
std = [
    'hex/std',
	'serde',
    'codec/std',
    'sp-std/std',
	'sp-core/std',
    "sp-runtime/std",
    'frame-support/std',
    'frame-system/std',
	"frame-benchmarking/std",
	'orml-tokens/std',
	"frame-benchmarking/std",
    'pallet-vesting-mangata/std',
    "mp-multipurpose-liquidity/std",
    "mp-traits/std",
    "parachain-staking/std",
]

runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]

try-runtime = [ "frame-support/try-runtime" ]
