[package]
name = "substrate-test-runtime-client"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-light = { version = "2.0.0" }
sp-consensus = { version = "0.8.0" }
sc-block-builder = { version = "0.8.0", path="/home/dev/substrate/client/block-builder"}
extrinsic-info-runtime-api = { path='/home/dev/substrate/primitives/extrinsic-info-runtime-api', version='2.0.0' }
substrate-test-client = { version = "2.0.0", path = "../../client" }
sp-core = { version = "2.0.0"}
substrate-test-runtime = { version = "2.0.0", path = "../../runtime" }
sp-runtime = { version = "2.0.0"}
sp-api = { version = "2.0.0"}
sp-blockchain = { version = "2.0.0"}
codec = { package = "parity-scale-codec", version = "1.3.1" }
sc-client-api = { version = "2.0.0"}
sc-consensus = { version = "0.8.0"}
sc-service = { version = "0.8.0", default-features = false}
futures = "0.3.4"
