[package]
name = "pallet-bridge"
description = "Artemis Bridge Pallet"
version = "0.1.1"
edition = "2018"
authors = ["Snowfork <contact@snowfork.com>"]
repository = "https://github.com/Snowfork/polkadot-ethereum"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies.serde]
package = "serde"
optional = true
version = "1.0.101"
features = ["derive"]

[dependencies.codec]
default-features = false
features = ["derive"]
package = "parity-scale-codec"
version = "1.3.4"

[dependencies.frame-support]
default-features = false
version = "2.0.0"

[dependencies.frame-system]
default-features = false
version = "2.0.0"

[dependencies.sp-core]
default-features = false
version = "2.0.0"

[dependencies.sp-std]
default-features = false
version = "2.0.0"

[dependencies.sp-io]
default-features = false
version = "2.0.0"

[dependencies.sp-runtime]
default-features = false
version = "2.0.0"

[dependencies.artemis-core]
default-features = false
path = "../../primitives/core"


[dependencies]
hex-literal = { version = "0.3.1", default-features = true }
frame-benchmarking = { version = "2.0.0", default-features = false, optional = true }

[dev-dependencies]
pallet-verifier = {path = "../verifier"}
artemis-erc20-app = {path = "../erc20-app"}
artemis-eth-app = {path = "../eth-app"}
artemis-asset = {path = "../bridged-asset"}
orml-tokens = {path = "../tokens", default-features = false, version="0.3.1"}
orml-traits = {default-features = false, version="0.3.1"}

[features]
default = ["std"]
std = [
		"serde",
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "artemis-core/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"sp-runtime/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
]
